### ISSUE TITLE
Enable Export to PDF / EPUB / MOBI

### ISSUE THREAD

**Issue by public-daniel** [chiphuyen/ml-interviews-book#7]
It looks like MathJAX-Node dependency is using a deprecated API. This will probably get resolved upstream, but just in case anyone else wants to export, there is a workaround:

Modify `node_modules/mathjax-node/lib/mj-single.js` on line 540 from

`result.speakText = speech.processExpression(result.mml);` 

to

 `result.speakText = speech.toSpeech(result.mml);`

Source for workaround: https://github.com/kgryte/tex-equation-to-svg/issues/2#issuecomment-411023604

**Comment by mikhaildubov** [comment]
Hi @public-daniel, would you mind sharing the PDF you got? Doesn't work for me even with the fix above. Thanks

**Comment by BellmannRichard** [comment]
@public-daniel  what about sharing the PDF? Thanks!

**Comment by animesh-007** [comment]
Hi, 

PFA for the pdf version of the book. I hope the authors of the book have no issue with this.😓
Thank you @Aryaman1706 for helping me in converting to the pdf version.

Regards,
Animesh
[mybook.pdf](https://github.com/chiphuyen/ml-interviews-book/files/6760572/mybook.pdf)

**Comment by chiphuyen** [comment]
Hi @animesh-007, this is amazing. I just sent you an email with a follow-up question about PDF rendering. Thank you so much! 

> Hi,
> 
> PFA for the pdf version of the book. I hope the authors of the book have no issue with this.😓
> Thank you @Aryaman1706 for helping me in converting to the pdf version.
> 
> Regards,
> Animesh
> [ml-interviews-book.pdf](https://github.com/chiphuyen/ml-interviews-book/files/6760580/ml-interviews-book.pdf)

**Comment by animesh-007** [comment]
> ml-interviews-book.pdf

Hi @chiphuyen. I tried to answer your follow-up question in the email. Hope the problem is resolved now. 😇

**Comment by chiphuyen** [comment]
Thanks Animesh! Yep we're working on it, just some few formatting problems left!

> > ml-interviews-book.pdf
> 
> Hi @chiphuyen. I tried to answer your follow-up question in the email. Hope the problem is resolved now. 😇

**Comment by karelin** [comment]
hello all,
Is it possible to provide some clues how the book in PDF or EPUB can be created?
(libraries, tools, ...)

**Comment by IanQS** [comment]
@animesh-007

Is the url you posted up-to-date? If not could you post instructions as to how you generated it? I'd really appreciate it

**Comment by jordandraper** [comment]
> @animesh-007
> 
> Is the url you posted up-to-date? If not could you post instructions as to how you generated it? I'd really appreciate it

Here is a PDF I just generated from the most recent commit. The instructions provided by @public-daniel still work perfectly https://github.com/chiphuyen/ml-interviews-book/issues/7#issue-930765633.
[ml-interviews-book.pdf](https://github.com/chiphuyen/ml-interviews-book/files/12083897/ml-interviews-book.pdf)

**Comment by dsvolkov** [comment]
And here is recent [ml-interview-book.epub](https://drive.google.com/file/d/1LMb4zh73Kz6RTKFM62nYZgbnxolBI7aa/view?usp=sharing)

**Comment by goyalyashpal** [comment]
```console
$ npm install
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated abab@1.0.4: Use your platform's native atob() and btoa() methods instead
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be p
roblematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

$ npx honkit pdf ./ ./ml-interviews-book.pdf
Need to install the following packages:
honkit@5.1.4
Ok to proceed? (y) y

npm warn deprecated try-resolve@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
(node:9508) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ReferenceError: Failed to load HonKit's plugin module: "mathjax" is not found.

cwd: ...\ml-interviews-book-master
baseDir:


    at PluginResolver.resolvePluginPackageName (%LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\honkit\lib\plugins\PluginResolver.js:78:19)
    at %LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\honkit\lib\plugins\loadForBook.js:26:34
    at %LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\immutable\dist\immutable.js:3016:46
    at List.__iterate (%LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\immutable\dist\immutable.js:2206:13)
    at mappedSequence.__iterateUncached (%LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\immutable\dist\immutable.js:3015:23)
    at seqIterate (%LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\immutable\dist\immutable.js:604:16)
    at IndexedSeq.__iterate (%LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\immutable\dist\immutable.js:320:14)
    at IndexedIterable.toArray (%LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\immutable\dist\immutable.js:4258:23)
    at List [as constructor] (%LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\immutable\dist\immutable.js:2065:62)
    at reify (%LOCALAPPDATA%\npm-cache\_npx\8ad405cc3f853826\node_modules\immutable\dist\immutable.js:3570:37)

```

**Comment by vanguard478** [comment]
I also encountered the `ReferenceError: Failed to load HonKit's plugin module: "mathjax" is not found.` error.
To resolve this i installed some the packages as below:
```bash
$ npm install --save-dev honkit@^6.0.3
$ npm install --save gitbook-plugin-ga@^2.0.0
$ npm install --save git+https://github.com/algorithm-archivists/plugin-mathjax.git
$ npm install 
## and finally this to create the pdf 
$ npx honkit pdf . ml-interviews-book.pdf 
``` 
Try running this `npx honkit pdf . ml-interviews-book.pdf` in an IDE so you can look at the error and got to the file directly ( I used VSCode) . First run would throw an error , where as mentioned by @public-daniel , you have to modify the file `mj-single.js` on Line 540 (for me it was located at `./node_modules/mathjax-node/lib/mj-single.js`.
From  
```js
//Original
result.speakText = speech.processExpression(result.mml);
//to 
//Modified 
result.speakText = speech.toSpeech(result.mml);
```

The changed the `package.json` file  as below :
```json
{
  "name": "ml-interviews-book",
  "description": "A book on ML interviews",
  "version": "0.0.1",
  "maintainers": [
    {
      "name": "Chip Huyen"
    }
  ],
  "dependencies": {
    "gitbook-plugin-ga": "^2.0.0",
    "gitbook-plugin-mathjax": "github:algorithm-archivists/plugin-mathjax"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/chiphuyen/ml-interviews-book"
  },
  "license": "Copyright ©2021 Chip Huyen",
  "scripts": {
    "build": "honkit build",
    "serve": "honkit serve"
  },
  "homepage": "https://huyenchip.com/ml-interviews-book/",
  "devDependencies": {
    "honkit": "^6.0.3"
  }
}

```
